params = {
    'apiKey': '',
    'minRelevancyScore': '100',
    'placementId': '1',
    'resultsAttributeValues': '100',
    'productIdType': '',
    'results': '250',
    'showAttributes': '',
    'backfillResults': '0',
    'showRawUrl': '',
    'offersOnly': '',
    'startOffers': '0',
    'resultsOffers': 3,
    'merchantId': '',
    'attFilter': '',
    'freeShipping': '',
    'imageOnly': '',
    'showProductAttributes': '',
    'biddedOnly': '',
    'start': '0',
    'maxAge': '',
    'minMarkdown': '',
    'categoryId': '',
    'productId': '',
    'sort': 'relevancy_desc',
    'format': 'json',
    'zipCode': '',
    'brandId': '',
    'minPrice': '',
    'keyword': '',
    'maxPrice': '',
    'callback': 'callback',
    'attributeId': '',
    'attWeights': '',
    'publisherId': '69109',
    'resultsAttribute': '20',
  }

taxonomy_params = {'apiKey': 'apiKey', 'publisherId':'', 'placementId': '1', 'categoryId': '1',\
      'keyword': '', 'results': '50', 'format': 'json', 'sort': 'name_asc'}